expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL
error_log = /proc/self/fd/2
html_errors = Off
zend.exception_ignore_args = On
memory_limit = 256M
max_execution_time = 60
upload_max_filesize = 20M
post_max_size = 20M
date.timezone = Europe/Istanbul
opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 1
